version: '3.4'

services:
  restaurant:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  apigetway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  reservation:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

